# Generated by Django 5.1.6 on 2025-03-03 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('status', models.CharField(choices=[('Resolvido', 'Resolvido'), ('Em espera', 'Em espera'), ('Pendente', 'Pendente')], default='Em espera', max_length=45)),
                ('creation_date', models.DateField()),
                ('creation_time', models.TimeField()),
                ('finished', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
    ]
