# Generated by Django 5.1.6 on 2025-02-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assessment',
        ),
    ]
