# Generated by Django 5.1.6 on 2025-02-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Resolvido', 'Resolvido'), ('Em espera', 'Em espera'), ('Pendente', 'Pendente')], default='Em espera', max_length=45),
        ),
    ]
