# Generated by Django 5.1.6 on 2025-02-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creation_time',
            field=models.TimeField(),
        ),
    ]
